server:
  servlet:
    context-path: /restaurant
  port: 9090

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:6000/myschema?createDatabaseIfNotExist=true
    username: root
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  main:
    banner-mode: "off"
  jackson:
    deserialization:
      fail-on-unknown-properties: true

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
