server:
  servlet:
    context-path: /restaurant

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:6000/restaurant?createDatabaseIfNotExist=true
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  main:
    banner-mode: "off"
  jackson:
    deserialization:
      fail-on-unknown-properties: true

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

jwt:
  token:
    #секрет для токена, хранится на сервере
    secret: jwtbiappdemo
    #время жизни токена в миллисекундах
    expired: 3600000

web:
  cors: http://localhost:3001
  login: /auth/login
  create: /auth/create